## Writes finished reel packages to output/<timestamp>_<slug>/.
## FOLDER CONTRACT (owner: "มันดูเยอะแยะไปหมด"): the root holds ONLY the
## three files a human actually uses; every working paper goes into
## _เบื้องหลัง/ so the folder reads like a delivery, not a debug dump.
extends Node

const DELIVERABLES := {
	"script": "1_สคริปต์.md",
	"edit": "2_แคปชั่น.srt",
	"publish": "3_โพสต์.txt",  # plain text, paste-ready (no markdown)
}
const BEHIND := {
	"plan": "แผนงานผู้กำกับ.md",
	"research": "ข้อมูลค้นคว้า.md",
	"review": "รีวิวก่อนส่ง.md",
}


func write_package(request: Dictionary, results: Dictionary) -> String:
	var t := Time.get_datetime_dict_from_system()
	var stamp := "%04d%02d%02d_%02d%02d%02d" % [t.year, t.month, t.day, t.hour, t.minute, t.second]
	var dir_path := Config.project_dir().path_join("output").path_join(stamp + "_" + _slug(str(request.get("topic", "reel"))))
	var behind := dir_path.path_join("_เบื้องหลัง")
	DirAccess.make_dir_recursive_absolute(behind)

	var clean := request.duplicate()
	clean.erase("_file")
	_write(behind.path_join("request.json"), JSON.stringify(clean, "  "))

	for stage in DELIVERABLES:
		var text: String = str(results.get(stage, ""))
		if not text.is_empty():
			_write(dir_path.path_join(DELIVERABLES[stage]), text)
	var combined := "# Reel Package — %s\n\nGenerated by Agent Town on %s\n" % [str(request.get("topic", "untitled")), stamp]
	for stage in BEHIND:
		var text: String = str(results.get(stage, ""))
		if text.is_empty():
			continue
		_write(behind.path_join(BEHIND[stage]), text)
		combined += "\n\n---\n\n## %s\n\n%s" % [stage.capitalize(), text]
	_write(behind.path_join("รวมทุกขั้น.md"), combined)
	return dir_path


## Write the town's text deliverables INTO an existing folder (a reels clip's
## 05_EXPORTS) so a clip lands as ONE folder: the real -clean.srt/.mp4 plus the
## post caption and working papers. Deliberately does NOT write a script.md or
## caption.srt — the batch's own -clean.srt IS the clip's script/caption, and
## duplicating it was the "caption and script in different folders" confusion.
func write_clip_extras(dir_path: String, request: Dictionary, results: Dictionary) -> String:
	var behind := dir_path.path_join("_เบื้องหลัง")
	DirAccess.make_dir_recursive_absolute(behind)
	var clean := request.duplicate()
	clean.erase("_file")
	clean.erase("_partial")
	clean.erase("_batch")
	clean.erase("_ep")
	_write(behind.path_join("request.json"), JSON.stringify(clean, "  "))
	var post: String = str(results.get("publish", ""))
	if not post.is_empty():
		_write(dir_path.path_join("3_โพสต์.txt"), post)
	var combined := "# Clip Package — %s\n" % str(request.get("topic", "clip"))
	for stage in BEHIND:
		var text: String = str(results.get(stage, ""))
		if text.is_empty():
			continue
		_write(behind.path_join(BEHIND[stage]), text)
		combined += "\n\n---\n\n## %s\n\n%s" % [str(stage).capitalize(), text]
	var burn: String = str(results.get("burn_note", ""))
	if not burn.is_empty():
		_write(behind.path_join("การเผา.md"), burn)
		combined += "\n\n---\n\n## Burn\n\n%s" % burn
	_write(behind.path_join("รวมทุกขั้น.md"), combined)
	return dir_path


func _slug(topic: String) -> String:
	# keep Thai characters — folder names should read like the job did
	var s := topic.to_lower().strip_edges().replace(" ", "-")
	var re := RegEx.new()
	re.compile("[^a-z0-9ก-๙\\-]")
	s = re.sub(s, "", true).left(40)
	while s.contains("--"):
		s = s.replace("--", "-")
	return "reel" if s.length() < 3 else s


func _write(path: String, text: String) -> void:
	var f := FileAccess.open(path, FileAccess.WRITE)
	if f:
		f.store_string(text)
		f.close()
	else:
		EventBus.log_line.emit("Failed to write " + path)
