## Writes finished reel packages to output/<timestamp>_<slug>/.
extends Node

const STAGE_FILES := {
	"plan": "00_plan.md",
	"research": "01_research.md",
	"script": "02_script.md",
	"edit": "03_captions.srt",
	"publish": "04_publish.md",
	"review": "05_review.md",
}


func write_package(request: Dictionary, results: Dictionary) -> String:
	var t := Time.get_datetime_dict_from_system()
	var stamp := "%04d%02d%02d_%02d%02d%02d" % [t.year, t.month, t.day, t.hour, t.minute, t.second]
	var dir_path := Config.project_dir().path_join("output").path_join(stamp + "_" + _slug(str(request.get("topic", "reel"))))
	DirAccess.make_dir_recursive_absolute(dir_path)

	var clean := request.duplicate()
	clean.erase("_file")
	_write(dir_path.path_join("request.json"), JSON.stringify(clean, "  "))

	var combined := "# Reel Package — %s\n\nGenerated by Agent Town on %s\n" % [str(request.get("topic", "untitled")), stamp]
	for stage in STAGE_FILES:
		var text: String = str(results.get(stage, ""))
		if text.is_empty():
			continue
		_write(dir_path.path_join(STAGE_FILES[stage]), text)
		combined += "\n\n---\n\n## %s\n\n%s" % [stage.capitalize(), text]
	_write(dir_path.path_join("reel_package.md"), combined)
	return dir_path


func _slug(topic: String) -> String:
	var s := topic.to_lower().strip_edges().replace(" ", "-")
	var re := RegEx.new()
	re.compile("[^a-z0-9\\-]")
	s = re.sub(s, "", true).left(40)
	while s.contains("--"):
		s = s.replace("--", "-")
	return "reel" if s.length() < 3 else s


func _write(path: String, text: String) -> void:
	var f := FileAccess.open(path, FileAccess.WRITE)
	if f:
		f.store_string(text)
		f.close()
	else:
		EventBus.log_line.emit("Failed to write " + path)
